INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (1,'Kartična namira','CDCD','Gotovinska isplata','Isplata gotovine na bankomatu ili na šalteru banke');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (2,'Kartična namira','CDCB','Kartično plaćanje uz gotovinski povrat (Cashback)','Kupovina roba i usluga uz dodatnu isplatu gotovine na prodajnom mjestu');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (3,'Kartična namira','CDQC','Zamjenska gotovina','Kupovina roba koje su jednake gotovini poput kupona u kockarnicama.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (4,'Kartična namira','CDOC','Originalno odobrenje','Transakcija koja omogućuje primatelju kartice izvršenje odobrenja u korist računa vlasnika kartice. Za razliku od trgovačkog povrata, originalnom odobrenju nije prethodilo plaćanje karticom. Koristi se kod odobrenja temeljem dobitaka u igrama na sreću.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (5,'Upravljanje sredstvima (Cash Management)','ACCT','Upravljanje sredstvima - unutar banke','Transakcija prenošenja sredstava između dva računa istog vlasnika računa kod iste banke.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (6,'Upravljanje sredstvima (Cash Management)','CASH','Upravljanje sredstvima – izvan banke','Transakcija predstavlja opću instrukciju za upravljanje sredstvima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (7,'Upravljanje sredstvima (Cash Management)','COLL','Naplata','Transakcija predstavlja prikupljanje sredstava temeljem priljeva na račun ili izravnog terećenja');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (8,'Upravljanje sredstvima (Cash Management)','CSDB','Gotovinska isplata','Transakcija se odnosi na gotovinsku isplatu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (9,'Upravljanje sredstvima (Cash Management)','DEPT','Depozit','Transakcija se odnosi na uplatu depozita.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (10,'Upravljanje sredstvima (Cash Management)','INTC','Plaćanje unutar Grupe','Transakcija se odnosi na plaćanje unutar Grupe Odnosno na plaćanje između dva društava koja pripadaju istoj Grupi.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (11,'Upravljanje sredstvima (Cash Management)','LIMA','Upravljanje likvidnošću','Prijenos s računa iniciran radi pražnjenja računa ili svođenja stanja na nulu, cashpoolinga ili sweepinga');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (12,'Upravljanje sredstvima (Cash Management)','NETT','Saldiranje (netiranje)','Transakcija se odnosi na izvršavanje saldiranja (netiranja).');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (13,'Komercijalna plaćanja','AGRT','Poljoprivredni transfer','Transakcija se odnosi na plaćanje u poljoprivredi.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (14,'Komercijalna plaćanja','AREN','Knjiženje potraživanja','Transakcija se odnosi na knjiženje potraživanja');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (15,'Komercijalna plaćanja','BEXP','Poslovni troškovi','Transakcija se odnosi na plaćanje poslovnih troškova.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (16,'Komercijalna plaćanja','BOCE','Knjiženje konverzije u Back Office-u','Transakcija se odnosi na plaćanje koje je povezano sa knjiženjem konverzije u Back Office-u');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (17,'Komercijalna plaćanja','COMC','Komercijalno plaćanje','Transakcija se odnosi na plaćanje komercijalnog kredita ili duga po kreditu');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (18,'Komercijalna plaćanja','CPYR','Autorsko pravo','Transakcija se odnosi na plaćanje autorskog prava.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (19,'Komercijalna plaćanja','GDDS','Kupoprodaja roba','Transakcija se odnosi na kupovinu ili prodaju roba.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (20,'Komercijalna plaćanja','GDSV','Kupoprodaja roba i usluga','Transakcija se odnosi na kupovinu i prodaju roba I usluga.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (21,'Komercijalna plaćanja','GSCB','Kupoprodaja roba i usluga uz gotovinski povrat','Transakcija se odnosi na kupovinu i prodaju roba I usluga uz gotovinski povrat.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (22,'Komercijalna plaćanja','LICF','Naknada za licencu','Transakcija predstavlja plaćanje naknade za licencu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (23,'Komercijalna plaćanja','POPE','Knjiženje prodajnog mjesta','Transakcija se odnosi na plaćanje vezano prodajno mjesto');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (24,'Komercijalna plaćanja','ROYA','Tantijemi / Prihodi od autorskog prava','Transakcija predstavlja plaćanje tantijema/prihoda s osnova autorskog prava.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (25,'Komercijalna plaćanja','SCVE','Kupoprodaja usluga','Transakcija se odnosi na kupovinu i prodaju usluga.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (26,'Komercijalna plaćanja','SUBS','Pretplata','Transakcija se odnosi na plaćanje informacije ili pretplate');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (27,'Komercijalna plaćanja','SUPP','Plaćanje dobavljaču','Transakcija se odnosi na plaćanje dobavljaču.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (28,'Komercijalna plaćanja','TRAD','Trgovačke usluge','Transakcija se odnosi na plaćanje trgovačkih usluga.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (29,'Potrošač','CHAR','Plaćanje u dobrotvorne svrhe','Transakcija predstavlja plaćanje u dobrotvorne svrhe.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (30,'Potrošač','COMT','Konsolidirano plaćanje treće strane za račun potrošača','Transakcija predstavlja plaćanje koje obavlja treća strana ovlaštena za prikupljanje sredstava radi plaćanja u ime i za račun potrošača.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (31,'Financije','CLPR','Otplata glavnice kredita za automobil','Transakcija predstavlja plaćanje otplate glavnice kredita za automobil.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (32,'Financije','DBTC','Plaćanje putem terećenja','Plaćanje temeljem naloga za terećenje');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (33,'Financije','GOVI','Državno osiguranje','Transakcija se odnosi na plaćanje državnog osiguranja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (34,'Financije','HLRP','Otplata stambenog kredita','Transakcija se odnosi na otplatu stambenog kredita.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (35,'Financije','INPC','Premija osiguranja za vozilo','Transakcija predstavlja plaćanje premije osiguranja za vozilo.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (36,'Financije','INSU','Premija osiguranja','Transakcija predstavlja plaćanje premije osiguranja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (37,'Financije','INTE','Kamata','Transakcija predstavlja plaćanje kamate.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (38,'Financije','LBRI','Osiguranje od ozljede na radu','Transakcija predstavlja plaćanje osiguranja od ozljede na radu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (39,'Financije','LIFI','Životno osiguranje','Transakcija predstavlja plaćanje životnog osiguranja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (40,'Financije','LOAN','Zajam','Transakcija se odnosi na odobrenje zajma zajmoprimcu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (41,'Financije','LOAR','Otplata zajma','Transakcija se odnosi na otplatu zajma zajmodavcu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (42,'Financije','PPTI','Osiguranje imovine','Transakcija predstavlja plaćanje osiguranja imovine.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (43,'Financije','RINP','Obročno plaćanje','Transakcija se odnosi na plaćanje ponavljajućih rata u redovitim intervalima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (44,'Financije','TRFD','Zaklada','Transakcija koja se odnosi na plaćanje zaklade.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (45,'Općenito','ADVA','Predujam','Transakcija predstavlja plaćanje predujma/avansa.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (46,'Općenito','CBFF','Kapitalna štednja','Transakcija se odnosi na kapitalnu štednju, odnosno štednju za umirovljenje.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (47,'Općenito','CCRD','Plaćanje kreditnom karticom','Transakcija se odnosi na plaćanje kreditnom karticom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (48,'Općenito','CDBL','Plaćanje troškova učinjenih kreditnom karticom','Transakcija se odnosi na plaćanje računa za troškove učinjene kreditnom karticom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (49,'Općenito','CFEE','Naknada za opoziv/storno','Transakcija se odnosi na plaćanje naknade za opoziv/storno.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (50,'Općenito','COST','Troškovi','Transakcija se odnosi na plaćanje troškova.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (51,'Općenito','DCRD','Plaćanje troškova učinjenih debitnom karticom','Transakcija se odnosi na plaćanje troškova učinjenih debitnom karticom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (52,'Općenito','GOVT','Plaćanje državi/države','Transakcija predstavlja plaćanje državnom tijelu ili plaćanje od strane državnog tijela.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (53,'Općenito','ICCP','Neopozivo plaćanje kreditnom karticom','Transakcija predstavlja povrat plaćanja s izvršenog kreditnom karticom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (54,'Općenito','IDCP','Neopozivo plaćanje debitnomkarticom','Transakcija predstavlja povrat plaćanja Izvršenog debitnom karticom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (55,'Općenito','IHRP','Plaćanje rate pri kupnji na otplatu','Transakcija predstavlja otplatu rate kod kupnje na otplatu.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (56,'Općenito','INSM','Rata','Transakcija se odnosi na plaćanje rate/obroka.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (57,'Općenito','MSVC','Višenamjenske usluge','Transakcija se odnosi na plaćanje višenamjenskih usluga.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (58,'Općenito','NOWS','Nenavedeno','Transakcija se odnosi na plaćanje za usluge koje nisu drugdje navedene.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (59,'Općenito','OFEE','Početna naknada (Opening Fee)','Transakcija se odnosi na plaćanje početne naknade.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (60,'Općenito','OTHR','Ostalo','Druga vrsta plaćanja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (61,'Općenito','PADD','Unaprijed odobreno terećenje','Transakcija se odnosi na unaprijed odobreni nalog za terećenje.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (62,'Općenito','PTSP','Uvjeti plaćanja','Transakcija se odnosi na specifikaciju uvjeta plaćanja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (63,'Općenito','RCKE','Ponovna prezentacija čeka','Transakcija se odnosi na plaćanje vezano za ponovnu prezentaciju čeka.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (64,'Općenito','RCPT','Plaćanje potvrde','Transakcija se odnosi na izdavanje potvrde o provedenom plaćanju.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (65,'Općenito','REFU','Povrat','Transakcija predstavlja povrat sredstava.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (66,'Općenito','RENT','Najam','Transakcija predstavlja plaćanje najma.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (67,'Općenito','STDY','Studiranje','Transakcija se odnosi na plaćanje troškova studiranja/školarine.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (68,'Općenito','TELI','Plaćanje putem telefona','Transakcija se odnosi na plaćanje koje je inicirano telefonom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (69,'Općenito','WEBI','Plaćanje putem interneta','Transakcija se odnosi na plaćanje koje je inicirano internetom.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (70,'Ulaganje','ANNI','Anuitet','Transakcija se odnosi na plaćanje auniteta kredita, osiguranja, ulaganja i dr.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (71,'Ulaganje','CMDT','Plaćanje roba','Transakcija predstavlja plaćanje roba.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (72,'Ulaganje','DERI','Derivativi (izvedenice)','Transakcija se odnosi na poslove sderivativima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (73,'Ulaganje','DIVD','Dividenda','Transakcija predstavlja plaćanje dividendi.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (74,'Ulaganje','FREX','Kupoprodaja deviza','Transakcija se odnosi na poslove deviznog tržišta.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (75,'Ulaganje','HEDG','Hedging','Transakcija se odnosi na operaciju hedginga.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (76,'Ulaganje','PRME','Plemeniti metali','Transakcija se odnosi na poslovanje s plemenitim metalima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (77,'Ulaganje','SAVG','Štednja','Prijenos na račun štednje/mirovine.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (78,'Ulaganje','SECU','Vrijednosni papiri','Transakcija predstavlja plaćanje vrijednosnih papira.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (79,'Ulaganje','TREA','Riznični transferi','Transakcija se odnosi na riznično poslovanje.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (80,'Zdravstvo','ANTS','Usluge anestezije','Transakcija predstavlja plaćanje za usluge anestezije.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (81,'Zdravstvo','CVCF','Usluge skrbi za rekonvalescente','Transakcija predstavlja plaćanje za usluge skrbi za rekonvalescente.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (82,'Zdravstvo','DMEQ','Medicinska oprema','Transakcija predstavlja plaćanje za nabavu trajne medicinske opreme');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (83,'Zdravstvo','DNTS','Zubarske usluge','Transakcija predstavlja plaćanje za zubarske usluge.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (84,'Zdravstvo','HLTC','Kućna njega bolesnika','Transakcija predstavlja plaćanje za usluge kućne njege bolesnika.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (85,'Zdravstvo','HLTI','Zdravstveno osiguranje','Transakcija predstavlja plaćanje zdravstvenog osiguranja.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (86,'Zdravstvo','HSPC','Bolnička njega','Transakcija predstavlja plaćanje za usluge bolničke njege.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (87,'Zdravstvo','ICRF','Ustanova socijalne skrbi','Transakcija predstavlja plaćanje usluga ustanove socijalne skrbi.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (88,'Zdravstvo','LTCF','Ustanova dugoročne zdravstvene skrbi','Transakcija predstavlja plaćanje usluga ustanove dugoročne zdravstvene skrbi.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (89,'Zdravstvo','MDCS','Zdravstvene usluge','Transakcija predstavlja plaćanje za zdravstvene usluge.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (90,'Zdravstvo','VIEW','Oftalmološke/okulističke usluge','Transakcija predstavlja plaćanje za oftamološke/okulističke usluge.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (91,'Plaća & naknade','ALMY','Plaćanje alimentacije','Transakcija predstavlja plaćanje alimentacije.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (92,'Plaća & naknade','BECH','Dječji doplatak','Transakcija se odnosi na plaćanje kojim se pomaže roditelju/staratelju u uzdržavanju djeteta.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (93,'Plaća & naknade','BENE','Naknada za nezaposlenost/invaliditet','Transakcija se odnosi na plaćanje osobi koja je nezaposlena/invalid.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (94,'Plaća & naknade','BONU','Novčana nagrada (bonus)','Transakcija se odnosi na plaćanje novčane nagrade (bonusa).');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (95,'Plaća & naknade','COMM','Provizija','Transakcija predstavlja plaćanje provizije.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (96,'Plaća & naknade','CSLP','Isplata socijalnih zajmova društava banci','Transakcija predstavlja plaćanje društva banci u svrhu financiranja socijalnih zajmova zaposlenicima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (97,'Plaća & naknade','GVEA','Austrijski državni službenici, Kategorija A','Transakcija predstavlja plaćanje kategoriji A austrijskih državnih službenika.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (98,'Plaća & naknade','GVEB','Austrijski državni službenici, Kategorija B','Transakcija predstavlja plaćanje kategoriji B austrijskih državnih službenika');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (99,'Plaća & naknade','GVEC','Austrijski državni službenici, Kategorija C','Transakcija predstavlja plaćanje kategoriji C austrijskih državnih službenika');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (100,'Plaća & naknade','GVED','Austrijski državni službenici, Kategorija D','Transakcija predstavlja plaćanje kategoriji D austrijskih državnih službenika');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (101,'Plaća & naknade','PAYR','Platni spisak','Transakcija se odnosi na isplatu plaća prema platnom spisku.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (102,'Plaća & naknade','PENS','Mirovine','Transakcija predstavlja isplatu mirovine.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (103,'Plaća & naknade','PRCP','Plaćanje troškova','Transakcija se odnosi na plaćanje troškova.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (104,'Plaća & naknade','SALA','Plaće','Transakcija predstavlja isplatu plaće.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (105,'Plaća & naknade','SSBE','Socijalna pomoć','Transakcija predstavlja naknadu za socijalnu pomić odnosno plaćanje kojeg izvršava država kao socijalnu potporu pojedincima.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (106,'Porez','ESTX','Porez na nasljedstvo','Transakcija se odnosi na plaćanje poreza na nasljedstvo.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (107,'Porez','HSTX','Porez na stambeni prostor','Transakcija se odnosi na plaćanje poreza na stambeni prostor.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (108,'Porez','INTX','Porez na dohodak','Transakcija se odnosi na plaćanje poreza na dohodak.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (109,'Porez','NITX','Porez na neto dohodak','Transakcija se odnosi na plaćanje poreza na neto dohodak');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (110,'Porez','TAXS','Plaćanje poreza','Transakcija predstavlja plaćanje poreza.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (111,'Porez','VATX','Plaćanje poreza na dodanu vrijednost','Transakcija predstavlja plaćanje poreza na dodanu vrijednost.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (112,'Porez','WHLD','Porez po odbitku','Transakcija se odnosi na plaćanje poreza po odbitku.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (113,'Prijevoz','AIRB','Zračni','Transakcija predstavlja plaćanje za poslove vezane uz zračni prijevoz.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (114,'Prijevoz','BUSB','Autobusni','Transakcija predstavlja plaćanje za poslove vezane uz autobusni prijevoz.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (115,'Prijevoz','FERB','Trajektni','Transakcija predstavlja plaćanje za poslove vezane uz trajektni prijevoz.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (116,'Prijevoz','RLWY','Željeznički','Transakcija predstavlja plaćanje za poslove vezane uz željeznički prijevoz.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (117,'Komunalne usluge','CBTV','Račun za kabelsku TV','Transakcija se odnosi na plaćanje računa za kabelsku TV.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (118,'Komunalne usluge','ELEC','Račun za električnu energiju','Transakcija se odnosi na plaćanje računa za električnu energiju.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (119,'Komunalne usluge','ENRG','Energija','Transakcija se odnosi na plaćanje energije.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (120,'Komunalne usluge','GASB','Račun za plin','Transakcija se odnosi na plaćanje računa za plin.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (121,'Komunalne usluge','NWCH','Troškovi za mrežu','Transakcija se odnosi na plaćanje troškova za korištenje mreže.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (122,'Komunalne usluge','NWCM','Mrežna komunikacija','Transakcija se odnosi na plaćanje mrežne komunikacije.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (123,'Komunalne usluge','OTLC','Račun za ostale telekomunikacijske usluge','Transakcija se odnosi na plaćanje računa za ostale telekomunikacijske usluge.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (124,'Komunalne usluge','PHON','Račun za telefon','Transakcija se odnosi na plaćanje računa za telefon.');
INSERT INTO sifra_namjene(rbr,klasifikacija,sifra,naziv,definicija) VALUES (125,'Komunalne usluge','WTER','Račun za vodu','Transakcija se odnosi na plaćanje računa za vodu.');