version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.282
      - image: circleci/buildpack-deps:stretch

    working_directory: ~/banking-backend/banking-parent

    steps:
      # git pull
      - checkout:
          path: ~/banking-backend

      - setup_remote_docker    

      # setup testing env
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY

      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify
      - save_cache:
          paths:
          - ~/.m2
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports  
        
      # package into a jar
      - run: mvn clean package

      # build and push docker image to docker hub
      - run: docker build -t banking-backend .
      - run: docker tag banking-backend lahur.ddns.net:5000/banking-backend:$CIRCLE_BUILD_NUM
      - run: docker tag banking-backend lahur.ddns.net:5000/banking-backend:latest
      - run: docker push lahur.ddns.net:5000/banking-backend:$CIRCLE_BUILD_NUM
      - run: docker push lahur.ddns.net:5000/banking-backend:latest

      # store raw contents of src code
      - store_artifacts:
          path: banking-web/target/*.jar
          destination: banking-backend